[package]
name = "example_arbitrary"
version = "0.1.0"
authors = ["Simonas Kazlauskas <git@kazlauskas.me>"]
edition = "2018"

[workspace]
members = ["."]

[dependencies]
libfuzzer-sys = { path = "..", features = ["arbitrary-derive"] }
