[package]
authors = ["The rust-fuzz Project Developers"]
description = "A wrapper around LLVM's libFuzzer runtime."
edition = "2018"
license = "MIT/Apache-2.0/NCSA"
name = "libfuzzer-sys"
readme = "./README.md"
repository = "https://github.com/rust-fuzz/libfuzzer"
version = "0.3.2"

[dependencies]
arbitrary = "0.4.1"

[build-dependencies]
cc = "1.0"

[features]
arbitrary-derive = ["arbitrary/derive"]
