[package]
name = "rustproto"
version = "0.1.0"
authors = ["John Yang <johnyangk@apache.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2.14.0"
protoc-rust = "2.14.0"
