name:                           Docker Image Release

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  deploy-docker:
    name:                       Build Release
    runs-on:                    ubuntu-latest
    steps:
      - name:                   Checkout sources
        uses:                   actions/checkout@master
      - name:                   Install toolchain
        uses:                   actions-rs/toolchain@v1
        with:
          toolchain:            stable
          profile:              minimal
          override:             true
      - name:                   Deploy to docker hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: openethereum/openethereum
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: scripts/docker/alpine/Dockerfile
          tag_names: true
